nelmio_api_doc:
    documentation:
        info:
            title: Swivl Test
            description: This is a test task for Swivl!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc) # Accepts routes under / except /doc
